### ISSUE TITLE
Oxygen Loads All Font Weights (Performance Issue)

### ISSUE THREAD

**Issue by rasmushax** [soflyy/oxygen-bugs-and-features#1756]
Oxygen loads all font weights despite me specifying in the editor only to use three weights across two different fonts.
![image](https://user-images.githubusercontent.com/75442302/101066502-cb78f300-3596-11eb-97ba-1d506ab23291.png)
As you can see in the code, it makes a weirdly heavy request for not only the same font twice, but also for Array here:
![image](https://user-images.githubusercontent.com/75442302/101066218-658c6b80-3596-11eb-94dd-d22de9e78ed6.png)

This is what it calls:
https://fonts.googleapis.com/css?family=Open+Sans:700,regular,|Rajdhani:700,|Array:100,200,300,400,500,600,700,800,900|Rajdhani:100,200,300,400,500,600,700,800,900

According to my specifications, The 2nd call for Rajdhani should not occur (I only want 700 weight) and the Array call I have no idea why occurs.

As you can imagine, this results in load of unnecessary assets that impact performance.

**Comment by ikx94** [comment]
Please fix this in the next version. Also would appreciate if someone knows a temporary workaround as this is causing a big performance problem for my site.

**Comment by YammYcoding** [comment]
+1

**Comment by pr0jectile** [comment]
This is also the case when you set both Display and Text fonts to the same font. It loads twice. Needs to be fixed.

**Comment by fescobedov** [comment]
I have the same bug and it is affecting my Cumulative Layout Shift, here a screenshoot....Please Oxygen, fix the bug :(

![2021-02-23_17-10-19](https://user-images.githubusercontent.com/64970656/109138891-27e54c00-775b-11eb-96f3-6716355a4503.png)

**Comment by rasmushax** [comment]
> I have the same bug and it is affecting my Cumulative Layout Shift, here a screenshoot....Please Oxygen, fix the bug :(
> 
> ![2021-02-23_17-10-19](https://user-images.githubusercontent.com/64970656/109138891-27e54c00-775b-11eb-96f3-6716355a4503.png)

Agreed - I have no idea why they haven't made this an urgent thing to fix as it's a huge performance bottleneck and I can't imagine it'd be that time-consuming for them. Been following the latest releases closely and each time I get disappointed not to see this addressed in the changelog.

**Comment by stafi** [comment]
I have the exact same thing.

**Comment by mikeldoka1** [comment]
Why is this issue not addressed yet? Did anyone come with a workaround?

**Comment by mikeldoka1** [comment]
Why is this issue not addressed yet? Did anyone come with a workaround?

**Comment by jamescrabb** [comment]
Yep this should be resolved by now. 9months as a confirmed bug 😳

**Comment by mikeldoka1** [comment]
The issue still remains, just updated to 3.9 and i still get the same https://fonts.googleapis.com/css?family=Rubik:300,500,600,700,regular,|Poppins:300,500,600,700,regular,|Rubik:100,200,300,400,500,600,700,800,900|Array:100,200,300,400,500,600,700,800,900|Roboto:100,200,300,400,500,600,700,800,900|Poppins:100,200,300,400,500,600,700,800,900&display=swap

**Comment by BenUniqcode** [comment]
I agree with mikeldoka, I'm using 3.9 and this is not fixed. Oxy always loads all weights, as well as requesting the same weights multiple times, and also requesting the "Array" font! Fortunately Google seems to deal ok with the latter two problems (hope they don't make a font called "Array" anytime soon), but we are definitely always getting all weights of whichever fonts are specified.
