### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by MCampagnini** [soflyy/oxygen-bugs-and-features#177]
**Describe the bug**
I was having a jQuery conflict with another plugin. When in the editor I was getting '$ is not a function'.  I was not getting this error prior to 2.1.

![not a function](https://user-images.githubusercontent.com/13643139/54857177-4cfdf400-4cd4-11e9-89ce-1a35309acb34.jpg)

I replaced all $(this) occurrences with jQuery(this) in component-framework/angular/controllers/ui.min.js to resolve.

**Comment by Infusednl** [comment]
Hi there,

You can use the following code so you can use $ instead of jQuery:

(function($) {

    // Here you can now write jquery with a $ sign
    $('.my-class').toggleClass('.active');

    $(document).ready(function() {
        // Add code to run when the document is loaded
    });
})(jQuery);

I found this option here:
https://stackoverflow.com/questions/6635600/jquery-how-can-i-use-instead-of-jquery

So all credits go to the original author.

**Comment by Spellhammer** [comment]
This should be fixed in Oxygen 2.4 Beta 1, can you test and confirm?

**Comment by drank** [comment]
I tested with 2.4.1 and can confirm that the issue IS still there - using $ instead of jQuery in a JS code block leads to a "$ is not a function" error.

**Comment by drank** [comment]
@louisreingold, got it - you are right, that's not a bug - https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/

I was mislead by the comment that this should be fixed so I assumed you were working to fix that.

Thanks for explaining.

**Comment by louisreingold** [comment]
We fixed the originally reported issue.
