### ISSUE TITLE
https://placehold.it needs replacing with https://via.placeholder.com

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/oxygen-bugs-and-features#2159]
**Any bug report that doesn't include a Sandbox link or replication steps will be closed. If you can't provide these pieces of information, we're happy to help you via our official support channel instead: https://oxygenbuilder.com/support. You need to select "Something's broken and I need help" from the dropdown box on the left.**

**Describe the bug**
*A clear and concise description of what the bug is.*
https://placehold.it/ is used for image placeholders by default, this service is now dead and has been replaced by https://placeholder.com/ the certificate on https://placehold.it/ is also now invalid. The default placeholder links need replacing so https://placehold.it/600x100?text=no+screenshot becomes https://via.placeholder.com/600x100?text=no+screenshot as an example.

**A link to a Sandbox site where the bug has been reproduced https://oxygenbuilder.com/try? (REQUIRED)**
*Provide the link to a Sandbox install where the issue is present. If the issue only exists on a specific post or template, provide a direct link to that post or template.*
N/A

**IF YOU CAN'T PROVIDE A SANDBOX REPRODUCTION: Steps required to reproduce the bug:**
Add a standard image using the builder and it will insert a placeholder referencing https://placehold.it/

**If you can't fill out the above information, you should not be filing a bug report. Instead, contact us via https://oxygenbuilder.com/support with the details you have and we'll investigate your issue further.**

**Comment by NetOldie** [comment]
I found more then 8 urls with http://placehold.it in my installation. 
HSTS is used on my server and this causes problems when loading http: elements. 

For example, I can no longer change the design set via the install wizard. In the access log of the web server I get 403, 400 and 499 error messages.

After I exchanged http for https, it works perfectly again.

**Comment by KittenCodes** [comment]
This is fixed in v3.8 RC1.

**Comment by EmSixTeen** [comment]
Using Oxygen 3.8.2 and this is not fixed.

**Comment by smllguy** [comment]
Using Oxygen 3.9 not fixed...

**Comment by NetOldie** [comment]
It's just disappointing.
Using Oxygen 3.9 not fixed.

**Comment by stefan1959** [comment]
Fixed for me, i did a fresh install of 3.9

**Comment by tudou-wp** [comment]
Hey, guys
You could use Gooreplacer to redirect placehold.it to via.placeholder.com for a tempary fix.
https://chrome.google.com/webstore/detail/gooreplacer/jnlkjeecojckkigmchmfoigphmgkgbip
https://addons.mozilla.org/firefox/addon/gooreplacer/

```
https://placehold.it/*
regex
https://via.placeholder.com/
```

**Comment by smllguy** [comment]
> Fixed for me, i did a fresh install of 3.9

Strange, did the same thing on a new url (no caching involved) this morning, Still 41 reports

**Comment by JeusuDigital** [comment]
I can confirm this is fixed and has been since the issue was closed.

**Comment by smllguy** [comment]
@JeusuDigital Ok, could you explain to me how it's possible that I still get this with a fresh O2 3.9?

**Comment by JeusuDigital** [comment]
@smllguy not without knowing your setup no.
If you go here: https://oxygenbuilder.com/try/
Create a blank install, then create a new page and insert an image you can see it is fixed.

**Comment by NetOldie** [comment]
> @smllguy not without knowing your setup no. If you go here: https://oxygenbuilder.com/try/ Create a blank install, then create a new page and insert an image you can see it is fixed.

Take a look here: https://oxygen-qa97va4mb637.oxygen-demo.qsandbox.me/sample-page/
On a fresh oxygen installation the URL was changed but not the protocol to https

![image](https://user-images.githubusercontent.com/64497200/148071533-170c83df-72f2-4c0d-aebd-7f0a1147ae7a.png)

**Comment by smllguy** [comment]
![Desktop-screenshot (2)](https://user-images.githubusercontent.com/97090069/148080716-18dac7be-9d1a-4f55-af15-b91c00ec7808.jpg)

**Comment by JeusuDigital** [comment]
@NetOldie yes you are correct with the URL being non HTTPS, they should fix that. 
@smllguy you should probably open a new issue with full steps to reproduce so they can look at your particular use case.

**Comment by dfag86** [comment]
the problem still occurs. In the latest Oxygen. How to solve/fix it?

**Comment by iamjaydatt** [comment]
img.itisuniqueofficial.com – The Ultimate Image Placeholder Generator

Looking for a faster, cleaner, and more powerful placeholder generator than the rest? Try img.itisuniqueofficial.com – lightweight, super fast, and easy to use for developers, bloggers, and designers.

* Generate placeholders in any size and format
* Customize background, text, and colors
* Works instantly with simple URLs
* Faster than other placeholder tools

Learn how to use it here: [https://img.itisuniqueofficial.com/documentation.html](https://img.itisuniqueofficial.com/documentation.html)
