### ISSUE TITLE
OXYGEN 4.0 ALPHA 1 — Gravity Forms won't render on Front End after converting Shortcodes to json.

### ISSUE THREAD

**Issue by Flipback8** [soflyy/oxygen-bugs-and-features#2623]
OXYGEN 4.0 ALPHA 1
The moment you resign Shortcodes, all of your Gravity Forms stop rendering on the front end.
"Oxygen's is now using JSON instead of WordPress shortcodes to store your designs. Please sign shortcodes to convert them to new format right away."

[Sandbox Link](http://blushing-sheep.w5.wpsandbox.pro?upass=w6io6P75KUeO)

Screenshots of Backend and FrontEnd:

 ![Back End Rendering](https://snipboard.io/1KJs2k.jpg)

 ![Front End Not Rendering](https://snipboard.io/8b0HBh.jpg)

**Comment by madjedo** [comment]
A pattern is starting to emerge with 3rd party plugins using shortcodes. We seen this now in Wpgridbuilder, WPML and now this.

Hopefully this can be an easy fix for O2 dev team. Else this update scares me... :|

**Comment by Flipback8** [comment]
Yes, same issue with Fluent Forms. Something is happening where Shortcodes are not rendering.

**Comment by Spellhammer** [comment]
Reproduced and reported internally. Thanks for the report.

**Comment by madjedo** [comment]
Just to add one more plugin to the list:

wpforms.

Same issue.

**Comment by Daniel-Florian** [comment]
I know you guys have already figured there is a bug, but just wanted to add Piotnet forms shortcodes aren't working either

**Comment by Oskar993** [comment]
Seems like a global issue with shortcodes. None of mine shortcodes work either:

- Formcraft
- FiboSearch - AJAX Search for WooCommerce
- WooCommerce Side Cart Premium

**Comment by Spellhammer** [comment]
I expect that no shortcodes rendered via a Shortcode or Shortcode Wrapper element will work in the Alpha. Due to our switch to JSON, we need to update the logic that ensures shortcodes stored in element properties are executed as expected. This will be solved in the next alpha or beta.

**Comment by VinceBalk** [comment]
Any progress on this issue yet?

**Comment by Flipback8** [comment]
> Any progress on this issue yet?

This issue has been resolved in Oxygen Beta 1

**Comment by VinceBalk** [comment]
I still have issues in modal or off canvas. External plugin issue? Oxyextra off canvas.

**Comment by Flipback8** [comment]
> I still have issues in modal or off canvas. External plugin issue? Oxyextra off canvas.

I have confirmed that Shortcodes render correctly inside of Oxygen Modal.

Note that you must be on **Oxygen 4.0 Beta 1**
