### ISSUE TITLE
Oxygen really slow due to api-requests on every page load in the backend

### ISSUE THREAD

**Issue by annejan89** [soflyy/oxygen-bugs-and-features#3023]
On every page load in the Wordpress admin, Oxygen Builder makes 6 http-requests to http://oxygenbuilder.com/ fired by caller EDD_SL_Plugin_Updater_Oxygen->api_request().

Instead of connecting to http://oxygenbuilder.com/ all the requests are redirected to https://oxygenbuilder.com.
This make the whole Wordpress backend terribly slow. 

<img width="1363" alt="Schermafbeelding 2022-07-27 om 10 13 08" src="https://user-images.githubusercontent.com/10883495/181196806-ab3074ee-fac1-4999-83f9-419541105d2e.png">

After setting `define( 'WP_HTTP_BLOCK_EXTERNAL', TRUE ); `in wp-config.php it ignores all the requests so the backend is fast again. But is obviously not a long-term solution.

Using:
Wordpress 6.0.1
WooCommerce 6.7.0
Oxygen Builder 4.0.2
Oxygen Elements for WooCommerce 1.4
Oxygen Gutenberg Integration 1.4.3

**Comment by Spellhammer** [comment]
Unable to reproduce. Can you please let me know which specific pages in WP Admin you're seeing these requests on?

**Comment by annejan89** [comment]
Why is this issue being ignored? Such a simple fix with huge performance impact. Oxygen Builder became a legacy product?

**Comment by Spellhammer** [comment]
This is fixed in the forthcoming 4.1 beta 1. We'll close this and all related issues once that's released.

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.

**Comment by annejan89** [comment]
Issue still occurs in Oxygen 4.5 and Gutenburg + Woocommerce

![Scherm_afbeelding 2023-03-31 om 10 39 46](https://user-images.githubusercontent.com/10883495/229072997-0579bc46-493f-474f-9a5c-f31bc988af84.png)

Settings the following constants in wp-config.php probably the only way to go to get some performance on admin-pages back.

```
define('WP_HTTP_BLOCK_EXTERNAL', true);

define('WP_ACCESSIBLE_HOSTS', '*.wordpress.org ,wp-rocket.me, woocommerce.com, connect.advancedcustomfields.com, downloads.wordpress.org, api.wordpress.org, update.yithemes.com, wpgridbuilder.com, api.postmarkapp.com, smtp.postmarkapp.com');
```

![Scherm_afbeelding 2023-03-31 om 10 40 31](https://user-images.githubusercontent.com/10883495/229079346-069a6056-7213-4ecc-afa8-0a6079c0d7ff.png)
