### ISSUE TITLE
Leaving padding blank on menus gives error

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#364]
**Describe the bug**
If the padding setting inside Menu > Spacing is left blank (assuming should just default to none) it instead causes errors.

`Notice
: Undefined index: menu_padding-top in
/home/267877.cloudwaysapps.com/nyvwgdwkrz/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2343

Notice
: Undefined index: menu_padding-bottom in
/home/267877.cloudwaysapps.com/nyvwgdwkrz/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2344

Notice
: Undefined index: menu_padding-left in
/home/267877.cloudwaysapps.com/nyvwgdwkrz/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2345

Notice
: Undefined index: menu_padding-right in
/home/267877.cloudwaysapps.com/nyvwgdwkrz/public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2346
`

I was using custom CSS to give menu padding an 'em' value since only px is available for menu padding controls. So I needed to leave them blank to allow the CSS not to be overridden, but i can't.

<img width="301" alt="Screen Shot 2019-06-20 at 2 36 45 pm" src="https://user-images.githubusercontent.com/43051571/59818854-e935a680-9368-11e9-9b8a-713db4594035.png">

**Comment by drank** [comment]
I confirm this behavior - my debug.log is full of "Undefined index: menu_padding-top/bottom/left/right" notices and setting paddings for the menus removes them.

**Comment by wpsumo** [comment]
@KittenCodes Still an issue in 3.6 even if it's confirmed to be fixed in the changelog.

**Comment by KittenCodes** [comment]
@wpsumo I've not been able to reproduce this on a clean Sandbox site running v3.6.

Are you able to reproduce it on a Sandbox site? You can create one here: https://oxygenbuilder.com/try/.

**Comment by wpsumo** [comment]
Notice | Undefined index: full_shortcode | 4 | +wp-content/plugins/oxygen/component-framework/includes/tree-shortcodes.php:89 | Plugin: oxygen
-- | -- | -- | -- | --


You have above as well. I'm sure you can not reproduce it as you create a brand new menu on a clean v3.6 but once you have a menu form previous v3.5.x.x and update to v.3.6 the issue is not resolved. So replicating in a sandbox will not help you in this case. Hope you understand what I mean. Send tickets to support as well but your system as often is down and the confirmation emails ar ento sent so as always emails is not sent.. annoying to figure out it never got through once you sent it. As a user you never remember to save it down before "if it doesn't work", you just ecpect it to work.

**Comment by KittenCodes** [comment]
@wpsumo I've now tested using v3.5 and upgrading to v3.6. I'm not able to see the errors after upgrading. Is there likely to be a cache on your site that is causing the problem?

**Comment by wpsumo** [comment]
Hmm hard to crack as I have a PRO menu and upgrade but still see. Regerated shortcodes and css and cleared redis object cache, opcache and varnish without success, still seeing this php notices in query monitor.

**Comment by KittenCodes** [comment]
@wpsumo I've just spotted that the error you are seeing in Query Monitor is:

Undefined index: full_shortcode

Are you seeing Undefined index: menu_padding-top/bottom/left/right, which is the error this bug report relates to?

**Comment by wpsumo** [comment]
I see both :)

**Comment by KittenCodes** [comment]
@wpsumo If you'd like us to take a look at your site, please open a support ticket: https://oxygenbuilder.com/support.

**Comment by wpsumo** [comment]
@KittenCodes Please fix the support system 👍

**Comment by KittenCodes** [comment]
> Please fix the support system 👍

How are you trying to open a support ticket and what isn't working?

**Comment by wpsumo** [comment]
@KittenCodes Any update regarding this issue?

```
Notice (7)
Undefined index: menu_padding-top on line 2605 in file /public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
```
```
Notice (7)
Undefined index: menu_padding-bottom on line 2606 in file /public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
```

**Comment by wpsumo** [comment]
@KittenCodes and in the builder:

Notice | Undefined variable: show_gradient on line 167 in file /public_html/wp-content/plugins/oxygen/component-framework/toolbar/views/background.view.php
-- | --

**Comment by wpsumo** [comment]
@KittenCodes Still see issue with full_shortcode on templates using shortcode element.


`Notice (3) | Undefined index: full_shortcode on line 89 in file /public_html/wp-content/plugins/oxygen/component-framework/includes/tree-shortcodes.php`

**Comment by KittenCodes** [comment]
@wpsumo Are the errors you're adding to this thread caused by leaving the padding blank on the menu? If not, please open separate bug reports for each issue.

**Comment by wpsumo** [comment]
@KittenCodes 
>Are the errors you're adding to this thread caused by leaving the padding blank on the menu?

Yes, using Pro menu Desktop menu > Spacing, Align, Border and top and bottom padding is left empty
```
Notice (7)
Undefined index: menu_padding-top on line 2605 in file /public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
Notice (7)
Undefined index: menu_padding-bottom on line 2606 in file /public_html/wp-content/plugins/oxygen/component-framework/components/component.class.php
```

For:
`Notice (3) | Undefined index: full_shortcode on line 89 in file /public_html/wp-content/plugins/oxygen/component-framework/includes/tree-shortcodes.php`

No not related to this thread maybe but related to the same undefined index issue. once the shortcode element is used I see this.

**Comment by KittenCodes** [comment]
@wpsumo 

We have internal bug reports open for both of these issues. Unfortunately, I don't have an ETA for when they will be fixed.

**Comment by wpsumo** [comment]
@wpsumo Thanks for confirming, please just fix and get rid of the last undefined index bugs.

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.

**Comment by jvorld** [comment]
I'm using Oxygen 4.0.1 and I am still seeing these errors.
What can I do to resolve them, without changing my wp-config.php?

```
Warning
: Undefined array key "menu_padding-top" in
/usr/www/users/bauxfa/baufaktura/wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2767

Warning
: Undefined array key "menu_padding-bottom" in
/usr/www/users/bauxfa/baufaktura/wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2768
```

**Comment by chrizoo** [comment]
I am using 4.0.2 and have the same Problem in the footer ...

Warning
: Undefined array key "menu_padding-top" in
/www/kinsta/public/.../wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2767

Warning
: Undefined array key "menu_padding-bottom" in
/www/kinsta/public/.../wp-content/plugins/oxygen/component-framework/components/component.class.php
on line
2768

Any Idea how to fix this?

**Comment by jvorld** [comment]
@KittenCodes This bug should be reopened.

@chrizoo Phe sent me the following to fix this manually: "If it's something you need to do in the future, you need to comment out the three error lines shown in this screenshot, which is around line #86 of /oxygen/component-framework/components/classes/comments-list.class.php: [https://d.pr/i/iB4nSz](https://d.pr/i/iB4nSz)"

**Comment by LukeSetzer** [comment]
Even after the "fix" it still does not work for me, on php 7.4 everything is working, but on php 8.1 it gives me the same error.

Warning: Undefined array key "menu_padding-top" in /homepages/0/d692657659/htdocs/wordpress/wp-content/plugins/oxygen/component-framework/components/component.class.php on line 2581

![image](https://user-images.githubusercontent.com/107842109/189098563-6c219da9-6019-4d65-bd6d-5470202cf1b8.png)

![image](https://user-images.githubusercontent.com/107842109/189098601-27141191-cfbe-45ad-bd45-6d21ed323dd1.png)

**Comment by adrien-robert** [comment]
Oxygen 4.0.4 with PHP 7.4, still he menu-padding error @KittenCodes 

![image](https://user-images.githubusercontent.com/4320990/191558571-886ec0cd-e79c-4721-9fc8-c828bd25d1f7.png)

Could you please reopen this ticket as it doesn't seem fixed?

**Comment by Kpudlo** [comment]
@adrien-robert @LukeSetzer, are you able to provide some information on the steps you're taking to see this issue? I've been unable to see this notice when modifying Desktop Menu > Spacing, Align, Border of the Pro Menu.

**Comment by adrien-robert** [comment]
> @adrien-robert @LukeSetzer, are you able to provide some information on the steps you're taking to see this issue? I've been unable to see this notice when modifying Desktop Menu > Spacing, Align, Border of the Pro Menu.

You mean setting them to 0? Like this?
![image](https://user-images.githubusercontent.com/4320990/192582995-ca9d1eeb-c49a-46a2-ac09-a2d05a444441.png)

**Comment by adrien-robert** [comment]
Even after doing what I did in the screenshot above, I have the same PHP Notices (this is after clearing all cache)
![image](https://user-images.githubusercontent.com/4320990/192584386-cb4539f0-240d-49b9-b4ca-1bd629be3e7d.png)

**Comment by adrien-robert** [comment]
@Kpudlo Should I provide you access to the website so you can see the errors yourself? Are you part of the Oxygen team?

**Comment by Kpudlo** [comment]
@adrien-robert, yes, if you could send credentials to support@oxygenbuilder.com that would be appreciated. I've still not been able to recreate this with Oxygen 4.0.4 and PHP 7.4 or PHP 8.

**Comment by adrien-robert** [comment]
> @adrien-robert, yes, if you could send credentials to [support@oxygenbuilder.com](mailto:support@oxygenbuilder.com) that would be appreciated. I've still not been able to recreate this with Oxygen 4.0.4 and PHP 7.4 or PHP 8.

Email sent with all the details, I just have the Oxygen Menu from a Oxygen page and the PHP Notices still appear (it's because I don't have padding-top and padding-bottom set on the Oxygen Menu). So please fix this, we shouldn't receive PHP Notices if we didn't put a value inside a setting from an Oxygen module.

**Comment by StefanoTesla** [comment]
Oh my god I'm not the only one!!


PHP 7.4 is out of support now!! Fix this bug please!!

Oxigen 4.2

Two menus, one for desktop view and one for mobile hidden with media query

`wp-content/plugins/oxygen/component-framework/components/component.class.php:2596
CT_Component->build_css()
wp-content/plugins/oxygen/component-framework/components/component.class.php:2427
CT_Component->set_options()
wp-content/plugins/oxygen/component-framework/components/classes/menu.class.php:54
Oxy_Nav_Menu->add_shortcode()
wp-content/plugins/oxygen/component-framework/includes/templates.php:76
do_oxygen_elements()
wp-content/plugins/oxygen/component-framework/components/classes/div-block.class.php:48
CT_DIV_Block->add_shortcode()
wp-content/plugins/oxygen/component-framework/includes/templates.php:76
do_oxygen_elements()
wp-content/plugins/oxygen/component-framework/components/classes/section.class.php:70
CT_Section->add_shortcode()
wp-content/plugins/oxygen/component-framework/includes/templates.php:76
do_oxygen_elements()
wp-content/plugins/oxygen/component-framework/includes/templates.php:109
ct_template_output()
wp-content/plugins/oxygen/component-framework/includes/templates.php:183
ct_templates_buffer_start()
wp-includes/class-wp-hook.php:308
do_action('ct_builder_start')
wp-content/plugins/oxygen/component-framework/component-init.php:1240
oxy_print_cached_css()
wp-includes/class-wp-hook.php:308
do_action('wp_head')
wp-includes/general-template.php:3043
wp_head()
wp-content/plugins/oxygen/component-framework/oxygen-main-template.php:10`

**Comment by Spellhammer** [comment]
A fix for this is slated for 4.6.

There's still a chance it could be deferred for another release, but this is the target release at the moment.

**Comment by Spellhammer** [comment]
This should be fixed in the forthcoming 4.6 Beta 1.
