### ISSUE TITLE
(3.0 Alpha 2) - Repeater - ID's are duplicated

### ISSUE THREAD

**Issue by wplit** [soflyy/oxygen-bugs-and-features#432]
**Describe the bug**
Every post inside the loop has the same ID

**To Reproduce**
1. Add repeater element
2. Query posts
3. Add any elements inside repeater div
4. Inspect html on front end

**Expected behavior**
Each new post & all elements inside should have new unique IDs, or no IDs at all, just classes if they all need to be the same.

**What actually happens**
Every element inside the loop has the same ID in each post. It causes an error in chrome lighthouse 

<img width="745" alt="Screen Shot 2019-07-24 at 5 00 26 pm" src="https://user-images.githubusercontent.com/43051571/61772085-bf264700-ae34-11e9-9550-72c6c54bc7fe.png">

**Screenshots**
<img width="629" alt="Screen Shot 2019-07-24 at 4 56 02 pm" src="https://user-images.githubusercontent.com/43051571/61771832-21327c80-ae34-11e9-8e7a-0d6d3a046c7e.png">

**Comment by louisreingold** [comment]
I can't think of a good way to address this. If we change the IDs, all the styles will stop working, so we'd have to output duplicate styles for every ID in the repeater. When we originally built Oxygen we should have skipped IDs entirely and used exclusively classes, but we didn't, and it's too late to do that now.

**Comment by albertso** [comment]
Incrementing the ids would make them unique, and if we use classes to style the blocks, there shouldn't be any styles from the id's to repeat.

What would be helpful is some way to copy styles between classes and ids, and also a button to reset the styles in a block or class.

**Comment by wplit** [comment]
hmmm..

Incrementing the ids, then having to duplicate all the CSS to make it work doesn't sound ideal.

I would argue the IDs aren't needed at all with repeater elements, but i get it's built heavily into how the components work. If you could somehow...

- Prevent styles from being added until a class is added, on any element inside the repeater. 
- Don't output the IDs for these elements at all on the front end.

Or have a little warning above the class/id field saying, you're styling an element inside a  repeater, please use a class first, Less ideal, but slightly easier to implement.

**Comment by albertso** [comment]
How about if there is an option to disable using id for any kind of block, inside or outside a repeater?

For example a toggle button next to the id field that grays out the id so the user knows it's disabled.

The id could still be there if that's necessary for oxygen internally, but we'd have the option to not use it in frontend.

Also, to help in the workflow of transferring styles from one thing to another, and seeing what's in use, we could have a button to inspect the styles applied to a block or class, in raw css.

If we could copy/edit/paste/clear there any custom css and have them converted back to oxygen values, it would really help in moving stuff between stylesheets, ids and classes.

**Comment by alpabuz** [comment]
> 
> 
> I can't think of a good way to address this. If we change the IDs, all the styles will stop working, so we'd have to output duplicate styles for every ID in the repeater. When we originally built Oxygen we should have skipped IDs entirely and used exclusively classes, but we didn't, and it's too late to do that now.

It may be possible to implement the generation of styles for each element with reference to the parent ID and this is what to display in the user interface, such as: _dinamic_list-60-43> *: nth-child(0). And by the same principle for nested elements of each element: _dinamic_list-60-43> *: nth-child(0)> *: nth-child(0). Due to the impossibility of deleting the ID for each element, I think it is possible to implement ID regeneration with the addition of a new index after the element is added to the repeater (e.g. div_block-61-43-1, div_block-61-43-2, div_block-61-43-3 ...). At the same time, such IDs should not be involved in the generation of styles and not displayed in the user interface.

I apologize if I have not explained clearly or my idea is too delusional.

**Comment by srikat** [comment]
Video showing @wplit's workaround:

https://wpdevdesign.com/video-workaround-for-oxygen-repeaters-duplicate-ids-problem/

**Comment by knytl** [comment]
The jQuery workaround is handy, but still need to add code. I think it would be enough to be able to remove ID of element. Now when I delete ID it still output "id" which is not much better.

**Comment by alriksson** [comment]
@knytl Yeah but we also remove all IDs in within the dynamic fields. Such as if the user adds an ID to any element such as H1-H6 in the WYSIWYG editor. Those will be removed with the Jquery workaround as well.

**Comment by alriksson** [comment]
Same issue in Gutenberg blocks. If using the same block on the same page we have duplicate IDs. So technically the same issue and root cause.

**Comment by wplit** [comment]
Just linking to a workaround to search for duplicate IDs across the whole page, then remove them. Again, just jQuery code tho.

(see code in comments, not at the top)
[https://gist.github.com/wplit/7861b18ef34ffd955b43ddcacc9ef6e8](https://gist.github.com/wplit/7861b18ef34ffd955b43ddcacc9ef6e8)

This means any Oxygen sections created for client use with Gutenberg have to be 100% styled with classes, as we can't control when/where they are used on the site and if multiple versions of the same block will be used on the same page.

**Comment by fadlee** [comment]
I created simple plugin to fix this issue.

https://github.com/fadlee/oxygen-repeater-fix

![image](https://user-images.githubusercontent.com/334797/70491799-e906ae80-1b34-11ea-8097-3a753dfd3422.png)

This plugin doesn't modify any of Oxygen functionality. It just modify the output, the HTML and CSS code, using simple preg_replace.

**HTML mod**

- modify `oxy_dynamic_list` shortcode output, move defined ID to class
- store `oxy_dynamic_list` children IDs for CSS modification

**CSS mod**

- monitor CSS xlink request, and buffer the output
- for cached CSS, modify Oxygen CSS URI, so the request can be intercepted
- modify CSS based on IDs stored before
- CSS selector modification: `#child_id` => `#parent_id .child_id`

**Comment by alriksson** [comment]
@fadlee Great, will try it out during the day! Does it cover the gutenberg blocks as well? Same issue there.

**Comment by fadlee** [comment]
@alriksson Thanks for the feedback.

1. What kind of Guternberg blocks do you mean? 

This plugin developed specifically for Oxygen Repeater. I've tested Repeater in Guterberg block, and it works as expected. At least for me.

2. I have no idea.

3. I need more information to analyze this problem. Can you share the URLs that give 404 errors? Do you use caching plugin?

**Comment by alriksson** [comment]
> What kind of Guternberg blocks do you mean?

All gutenberg blocks created in Oxygen have duplicated ID's as well if same block is used more than once.

>This plugin developed specifically for Oxygen Repeater. I've tested Repeater in Gutenberg block, and it works as expected. At least for me.

For me, once I enable your plugin it breaks all styling and the universal.css file.

>I need more information to analyze this problem. Can you share the URLs that give 404 errors? Do you use caching plugin?

Yes using WP Rocket.

**Comment by fadlee** [comment]
@alriksson I have updated the plugin. Can you give another try? 

Don't forget to Regenerate Oxygen CSS.

**Comment by alriksson** [comment]
@fadlee Thanks, I will let you know as soon as I had time to test the new version. 
Does this one include gutenberg ID fix as well or only the bug fix for the repeater?

**Comment by fadlee** [comment]
@alriksson I fixed the CSS issue.

Gutenberg issue is a different problem, its more complicated. I don't think to implement in my simple plugin, that focus on specific repeater issue.

**Comment by alriksson** [comment]
>I fixed the CSS issue.

You did, it is now working as intended for the `<div>` but not for child elements in the repeater such as `<p>`. Could you make support to catch those as well?

> Gutenberg issue is a different problem, its more complicated. I don't think to implement in my simple plugin, that focus on specific repeater issue.

Okay, how come the ID issue in gutenberg blocks is more complicated once created with oxygen? Just curious. Maybe something you would like to look into as well? Really a bottleneck in my case and maybe for more people when I use TOC and can not do so with headlines created in Oxygen.

Would be very much appreciated. Maybe more code friendly guys like @wplit would enjoy to contribute 😄

**Comment by benhohner** [comment]
@louisreingold Sometimes apps need a major refactor to pave the way forward. ;) What's best for the long term growth of the community? More and more of the WordPress ecosystem is moving toward web standards compliance, and it's actually a boon because native web technologies are now so powerful. Maybe Oxygen can move away from an ID based styling system and toward BEM for v4.0? It would solve all sorts of cascade issues.

**Comment by vecchionico** [comment]
@KittenCodes Should we file a separate bug for the Gutenberg Block issue first mentioned by @alriksson or is it ok to deal with both issues in this very report? Just stumbled upon the Gutenberg Block issue myself and found this report while searching if it was already reported by someone else.

**Comment by KittenCodes** [comment]
@vecchionico There's no need to file a separate report.

**Comment by Lupul** [comment]
This issue also affects repeated js blocks like those created by the gallery element. (Ex: lightbox link works only on the first image)

**Comment by alriksson** [comment]
Only me that experience duplicated CSS selectors and styling with @fadlee oxygen fixer?
Anyone that has a similar solution to the Gutenberg duplicated ID issue.
Also would be nice to have a cleaner path than /oxygen-fix/. But not a biggie.

Default ID styling starts to become an issue, starting to become a bigger bottleneck. Good luck using the Gutenberg content block with quick links/jump links. Which only works if we use the_content and native clean headlines without oxygen IDs. Which is limiting us.

**Comment by alriksson** [comment]
@KittenCodes Any update on this issue? Same with Gutenberg blocks anyone with a php solution to solve these ones as well?
@fadlee Any chance you have time to look into this as well?

**Comment by shoelaced** [comment]
Is there any update on this issue? Incrementing the IDs would be ideal, since there are certain use cases where they're necessary. In my case, I'm trying to create a dynamic set of tabs, where the tab name and the tab content are members of an ACF repeater. In order to properly associate each tab with its content, it would be immensely helpful to have an ID# attached to each of a Repeater's children.

Or, alternatively, the Tab block would function as a Repeater, but I'm sure there are other use cases when numbering the Repeater children would be helpful.

**Comment by guit4eva** [comment]
+1 !!

**Comment by guit4eva** [comment]
This issue was opened a whole year ago, surely it should be viewed as urgent? It means scrolling to anchor points, lightbox etc within repeaters won't work correctly...

**Comment by shoelaced** [comment]
This issue really ought to have a higher priority. There are a whole host of problems it creates, from anchor scrolling to javascript. I understand that there's a consideration about breaking CSS but couldn't it at least be an option? Just put a checkbox in the settings that says "Use dynamic IDs" or something, and older sites whose CSS breaks can simply un-check the box. Or perhaps it could somehow only affect new Repeater elements, and not ones already saved.

Whatever the solution, it's a rather large bug.

**Comment by guit4eva** [comment]
I found a workaround for the anchor scrolling by adding a code block inside the repeater with a div id set to the_title(), works a treat:

`<div id="<?php echo trim(strtolower(str_replace(" ","",get_the_title())));?>"></div>`

 Unfortunately I don't know how to get things like Lightbox to work though..

**Comment by wpsumo** [comment]
@Spellhammer Popular issue to fix any update on this?

**Comment by touchdowntech** [comment]
> I can't think of a good way to address this. If we change the IDs, all the styles will stop working, so we'd have to output duplicate styles for every ID in the repeater. When we originally built Oxygen we should have skipped IDs entirely and used exclusively classes, but we didn't, and it's too late to do that now.

@louisreingold What if you disable the ability to edit ID's on elements nested inside the repeater? I don't know if that is possible or if it would cause other issues. When I started with Oxygen I exclusively design using classes. I'm thankful that I did. I think there should be more emphasis in the official Oxygen videos to style using classes.

**Comment by shoelaced** [comment]
It sounds to me like unless there can be a checkbox or something to enable/disable unique IDs on a per-site basis during a lonnnnnggggg deprecation period, someone's gonna have to develop a tool that can search through the database and convert the IDs to classes for each repeater. In my mind, leaving duplicate IDs in there forever simply because they weren't accounted for in the initial build isn't a viable, sustainable, or acceptable option. There needs to be some way to uniquely identify each repeater child if it's going to be done right, so IDs with an incremented number appended seems appropriate, but given that this is a reasonably active bug report it seems like a solution needs to be at least decided upon soon.

**Comment by mamaddi** [comment]
As mentioned by @guit4eva , because of this bug it's impossible to have the gallery element with lightbox in a repeater: only the first gallery's lightbox will work. 
Would it be feasible to add an option for the repeater element "Use unique IDs", that at the same time disables styling of the IDs? Not ideal, but it would solve this kind of issues.

**Comment by ds-codes** [comment]
Recommend fixing this **by tomorrow**, guys. ;) As a new Oxygen user this over-reliance on IDs for styles is kinda.. not supposed to be done.. ever. It's one of the first things we all learned in html/css camp when we were coding-toddlers and frankly, a paradoxically amateur-hour mistake for such a complex and, also frankly, amazing project like this. What a thing to do! But hey, I totally wasted like 2 or 3 days on this before realizing "maybe it's a known issue." So we all make silly mistakes... But this over.. NOW... please? Come on, y'all. I give you full permission to drop everything else.

_Sent with love and a little heartache_

**Comment by LauGau** [comment]
This duplicate ID is a real problem. Oxygen code is cleaner yes... but not valid if we use repeater...😣
It also breaks some translation plugin (like TranslatePress) and all links in repeaters are broken... 😖

**Comment by shoelaced** [comment]
It seems evident that this really needs to be fixed, but also that some kind of migration tool would need to be built to manage the transition. Yeah it's extra work that wouldn't have to be done if this had been considered when O2 was built, but here we are, and it's a pretty significant issue to leave unresolved. It seems though that the new 'copy styles to another selector' feature could help with this.

Putting a checkbox in the settings that would turn on/off incremented IDs would at least prevent CSS from breaking and let people turn it on when they're ready to deal with going through their repeaters to copy the styles to a class -- ideally checked by default on new installations and left un-checked when updating the plugin if the setting hasn't been set.

Better yet if there could be a search/replace tool of some kind that would change the instances of the ID to the new class in the global stylesheets as well (which frankly would be a useful feature on its own). Some kind of sitewide "swap this ID for this class or vice versa" feature that would update the global stylesheets and optionally also copy or move the styles using the new built-in functionality. 

Even better yet to create an automatic tool - i.e. O2 would search for repeaters, find those with repeated IDs, assign new IDs, convert the previous to a class, move/copy the styles to the class, and then go swap the `#` for a `.` in all the global stylesheets.

I'm not sure how the interface would work with dynamic IDs in the end but perhaps Repeaters and Easy Posts (and other things that *should* have repeater functionality like Tabs, Sliders, Accordions, etc., but I digress...) would need a completely separate selector dropdown, that is, they'd have the normal one for the class that gets applied to all children, and a separate one where we can select and style the individual IDs for specific children - dynamically populated based on the number of posts in the query.

I'm just throwing noodles at the wall at this point but there _are_ ways of fixing this. It just depends on what it'll take to do it, since none of them are easy. Shrugging and saying "whoops, can't change it now" really shouldn't be an option on the table.

**Comment by swinggraphics** [comment]
Following. Could we just get access to the repeater PHP, like we have for Easy Posts?

**Comment by swinggraphics** [comment]
> I can't think of a good way to address this. If we change the IDs, all the styles will stop working, so we'd have to output duplicate styles for every ID in the repeater. When we originally built Oxygen we should have skipped IDs entirely and used exclusively classes, but we didn't, and it's too late to do that now.

Create a new Repeater. New installs will use the new one, while old installs can use the bad one. Yes, validation, optimization, and best-practices should have been considered from the beginning, but it's never too late to make your all-encompassing site builder render valid code. I would _gladly_ pay the one-time fee all over again if I got a really good, solid build tool for it.

**Comment by wpsumo** [comment]
Any updates on this issue? Still issues in gutenberg blocks and repeaters. @fadlee solution throwing errors when using redis object cache and do not solve gutenberg blocks.

**Comment by LauGau** [comment]
Yes I'm still waiting (and hoping) for this one. Even if it's for an all new revamped product. Like an Oxygen 2 (or Dioxygen), whatever you call it, I am in.

**Comment by jamescrabb** [comment]
This is obviously causing the oxygen team some difficulties as it has been a long time and no progress. Let's hope something can be resolved with this as it goes against all best practices for web dev

**Comment by swinggraphics** [comment]
@jamescrabb Oxygen creates a lot of invalid code in numerous places, both in HTML and CSS. It just isn't something they care about at all.

**Comment by Spellhammer** [comment]
> Oxygen creates a lot of invalid code in numerous places, both in HTML and CSS. It just isn't something they care about at all.

@swinggraphics  Your participation is welcome, but making statements like "It just isn't something they care about at all" implies you actually know what you're talking about. You do not know what our internal development priorities look like.

Do not state assumptions about Oxygen or its development process and represent them as factual.

**Comment by swinggraphics** [comment]
Quite right. I apologize. I have edited my comment.

**Comment by schietegal** [comment]
+1

Are there any news on this?

**Comment by Riyad95** [comment]
Solution?:
Create a new repeater element OR add a checkbox (which is off by default) that'll remove all ids from children if it's checked.
This'll mean it's backwards compatible if people update Oxygen.

Upon checking the checkbox, any changes made to the ID will be ignored, you can show a box under that checkbox to let the user know. No need to block users from styling on IDs etc as that might complicate it.


If you're not fixing it anytime soon (it's been years), could we at least know why? And it's true that we might not know what your internal development priorities look like, so would it be possible to let us know what's taking priority over this?

**Comment by albertvisuals** [comment]
Gosh! Any news on this? This needs to be fixed asap! I also need to use TranslatePress as well as try to use a modal window inside of a repeater element. Guess this is the problem now... I would be perfectly happy if this would change with new installs, but please solve this issue!

**Comment by kevingeary** [comment]
Seems like the easiest fix is to create a Repeater 2.0 module that uses incremental IDs. Deprecate the old module, but leave it in Oxygen for a year to give people time to migrate away from it. In the meantime, all of us people who properly use classes to style things can use the 2.0 version and not have to worry about this issue anymore.

**Comment by albertvisuals** [comment]
@kevingeary Absolutely! That would be a prefect solution to include a Repeater 2.0, which uses incremental IDs

**Comment by albertvisuals** [comment]
Is there a script available, which could change the repeater behavior to incremental ids? There is one, which deletes the ids altogether, but incremental would be better. 
`jQuery(".oxy-dynamic-list").find("*[class^='ct-']").removeAttr('id');`

**Comment by albertvisuals** [comment]
Have heard back from oxygen support, because of a problem, which is there because of these duplicate ids. Sadly just a generic we don't disclose further development. Really? This bug is here since 2019! I really enjoy using oxygen, but this makes me annoyed. It's just such a big no-no to use duplicate IDs, and many users run into issues because of this. Just release a repeater 2.0 with incremental ids - that should be possible in 2 years of time!

**Comment by louisreingold** [comment]
Not sure if this solution would work, but...

What if we just have an option to not output IDs if an element is inside a Repeater? The option could be a checkbox on the Repeater, and not enabled by default. 

Enabling it obviously would mean your ID styles for elements inside a Repeater wouldn't work. But that's not a problem, since people who want to enable this option are going to use classes to style the Repeater's children.

Over the last year we've done a fantastic job fixing bugs and making Oxygen significantly more reliable. So let's compromise a little bit on code quality and ship this. It's not like this is the only bit of partially-digested spaghetti in the codebase.

When rendering a Repeater...
```php
global $isInRepeater;
$isInRepeater = true;
/* render contents */
$isInRepeater = false;
```

When outputting any element's HTML on the frontend...
```php
global $isInRepeater

/* when outputting the HTML ID attributes, wrap with... */
if (!$isInRepeater) {
 // ...
}
```

Is there something about the codebase that prevents a "hacky" solution like this or makes implementation more complicated than what I've described above?

@ilyakop @Spellhammer

I won't be commenting further.

**Comment by louisreingold** [comment]
Someone's gonna find this post in 5 years and accuse me of being a shitty developer. 🤷‍♀️

**Comment by wpsumo** [comment]
> Enabling it obviously would mean your ID styles for elements inside a Repeater wouldn't work. But that's not a problem, since people who want to enable this option are going to use classes to style the Repeater's children.

Sounds good. Might make sense to grayed out the ID selector to make the UI clear it's can't be styled if the setting is enabled.

**Comment by albertvisuals** [comment]
I have maybe found a workaround if you need to create a unique ID for each Div inside the repeater. 
Using a code block and create the DIV manually: 
`<div id="av-pdf-id<?php echo $file['id'];?>" style="height: 360px; width: 500px;"></div>`
This works with the Adobe PDF embed API, which was broken beforehand, so maybe that can be useful for others too.

**Comment by shoelaced** [comment]
If we're okay with adding a checkbox that would remove the IDs entirely, why aren't we okay with adding a checkbox that would increment them? It seems like there are a lot of situations where a unique ID for each repeater element would be helpful for Javascript.

**Comment by scmrecordings** [comment]
> Not sure if this solution would work, but...
> 
> What if we just have an option to not output IDs if an element is inside a Repeater? The option could be a checkbox on the Repeater, and not enabled by default.
> 

@louisreingold  I would go one step further and offer this checkbox on every element (and even offer a global option to default the disabling IDs checkbox to checked).

One of my biggest (and really only) frustrations with Oxygen beyond the repeater ID issue, is that I have to either leave a bunch of random IDs for all of the elements in my markup, or add an ID name manually for every single one. In my opinion, this is the one thing that stops the Oxygen code output from being as clean as hand coding. I would prefer to just work with classes except for when a specific element needs to be targeted (as I'm sure many other people would) and this would make Oxygen pretty much perfect in my book as far as code output goes.

**Comment by wpsumo** [comment]
Just migrate to classes without adding clsses to unviseral, let classes run in specific templates etc.

The duplicate ID issue is not limited to repeater. It's present in the gutenberg blocks as well.

**Comment by webenadam** [comment]
Are u kidding? remove those id's!

Is @louisreingold from oxygen's team? because "When we originally built Oxygen we should have skipped IDs entirely and used exclusively classes, but we didn't, and it's too late to do that now." answer is a warning sign to stay out of this plugin if it is. because it means this plugin is stuck! it won't stay up to date. this is so basic. if you don't fix this simple issue how can someone build a series website and count on this plugin to live with it through the years coming?

**Comment by wplit** [comment]
> this is so **basic**... if you don't fix this **simple issue**

i wouldn't be so quick to use words such as basic or simple when describing the problem of finding a way to remove one of the fundamental parts of Oxygen components. It's not just about preventing one attribute them from being output on the front end, there's all the issues of the styling & JS using IDs to identify elements for certain functionality etc.

**Comment by webenadam** [comment]
@wplit if you every followed a page builder's development life cycle, you would know that there is so much to consider and add with time. and yes, treating the id's is a very very basic fundamental feature. i'm not saying it's that easy (btw - it's also not that hard), but i'm saying it's very fundamental and if a developer decides not to treat that right away (this issue is 2 years old, and this problem is older) so you can probably guess it's going to be a very very slow development down the road. and it is (you can tell by other issues also, it's not the only one).

**Comment by Firsh** [comment]
> until now they didn't make any money

:D Nah, they do https://www.wpallimport.com too.

**Comment by conlumina** [comment]
Please try this, fresh out of the oven: https://conlumina.com/fix-oxygen-repeater-duplicate-ids/

**Comment by ayhanmalkoc** [comment]
> Please try this, fresh out of the oven: https://conlumina.com/fix-oxygen-repeater-duplicate-ids/

Thanks for this code. But it didn't work for me.

**Comment by KittenCodes** [comment]
> Thanks for this code. But it didn't work for me.

Did you activate the code after importing it to Code Snippets or Advanced Scripts?

**Comment by ayhanmalkoc** [comment]
> > Thanks for this code. But it didn't work for me.
> 
> Did you activate the code after importing it to Code Snippets or Advanced Scripts?

Yes, it's loaded with code snippets and it's active. I checked the repeater outputs, the ID is repeated.

**Comment by KittenCodes** [comment]
> Yes, it's loaded with code snippets and it's active. I checked the repeater outputs, the ID is duplicated.

Do you have any caching on the site that may need clearing?

**Comment by sandyhuner** [comment]
@conlumina the script is causing some problems with certain repeaters, see screenshot, please advise.

![repeater](https://user-images.githubusercontent.com/18009339/121479966-da6bb280-c9ca-11eb-9cf3-fd099c8677d0.png)

**Comment by v-marinkov** [comment]
> > Yes, it's loaded with code snippets and it's active. I checked the repeater outputs, the ID is duplicated.
> 
> Do you have any caching on the site that may need clearing?

Yeah, it didn't make a difference for me either:
parent repeater: `id="_dynamic_list-57-11"` 
childred all have: `id="div_block-58-11"`

**Comment by hsnyc** [comment]
I recently had the need to select a couple of individual elements inside a repeater when I came across this bug. I have addressed it in the mean time by selecting the link items inside the repeater and changing their ids incrementally. 

```
//Get all elements in Dynamic List
var ctLinks = document.querySelectorAll('#_dynamic_list-75-1584 .ct-link');

// update IDs
var newId = 'cm-pbm-ct-link_';

for (i = 0; i < ctLinks.length; i++) {
    ctLinks[i].id = newId + i.toString();
}
```
Then you can target individual elements. In my case I needed to prevent default on a few of the links so I just added those to an array:

```
var pdLinks = ['cm-pbm-ct-link_1', 'cm-pbm-ct-link_4'];

for (let index = 0; index < pdLinks.length; index++) {
	let tlink = document.getElementById(pdLinks[index]);

	tlink.addEventListener('click', (e) => {
		e.preventDefault();
                //etc..
	});
}
```

Make sure you copy the Id styles to a class on those links.

Sharing in case it helps anyone else out there.

Hope this bug gets resolved in a future release of Oxygen.

**Comment by nathanbitcheno** [comment]
> Please try this, fresh out of the oven: https://conlumina.com/fix-oxygen-repeater-duplicate-ids/

On my site it looks like this only works on "pages" that have the repeater element. Oxygen templates which also have the repeater element which is still defined by shortcode oxy_dynamic_list_3 don't seem to be affected by this. Any thoughts on how to address this or if I'm overlooking something simple?

**Comment by puipaktin** [comment]
Can the Oxygen team add a New Repeater element which solves the duplicate ID problem, while keeping the old one?
I think it's easier and "safer" to implement.
It's better to solve "future problems" and leave the old problems behind rather than doing nothing.

**Comment by andresbrx** [comment]
+1

**Comment by wpsumo** [comment]
It would not lighten the HTML document as well and make it cleaner and easier to read by removing all IDs. It could be an option which is disabled by default for years until the default switch will be on to later on fully switch to no ID.

As we style all elements with classes and don't think anybody leaves display attribute empty, why do we need ID and default styling on those. Users who want to style elements individually and not add classes can manually add IDs or keep the legacy item on. If users don't select a class or add a class a generated oxy-class will be generated on the item once they start using the UI to style and no class is assigned.

**Comment by wpsumo** [comment]
> Same issue in Gutenberg blocks. If using the same block on the same page we have duplicate IDs. So technically the same issue and root cause.

@Spellhammer This issue is also present in gutenberg blocks. A second opinion, keeping all IDs and adding them to data attributes is good for backwards compatibility but still clutter down for users who don't use IDs on repeaters, which I guess is many due to the duplicated issue. Maybe an option for us to use only class styling. Per repeater element? And another globally. ID should only be needed once a user add an ID just like classes today. Time to move away from auto generated IDs? :) And please consider removing the wrapper div on the repeater element once you anyhow are in the repeater code.

You always say ACF repeaters is complex to handle. How come, it's fairly simple using repeaters directly in php. Is it complex how oxygen is built and within oxygen not necessary to build a repeater based UI?

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.0.

**Comment by 0x7466** [comment]
This issue is still present when you use a repeater in a repeater.

**Comment by wplit** [comment]
> This issue is still present when you use a repeater in a repeater.

Just tested it, not seeing any duplicate IDs. Are you doing something custom perhaps that could be causing it?
