### ISSUE TITLE
Icons preview not show in 2.2 Alpha 1

### ISSUE THREAD

**Issue by Airbees** [soflyy/oxygen-bugs-and-features#46]
**Screenshots**

![snimek obrazovky 2019-02-01 v 20 48 51](https://user-images.githubusercontent.com/47257510/52145997-d1cc7a00-2662-11e9-8011-653ce5a7c6fa.png)
![snimek obrazovky 2019-02-01 v 20 48 39](https://user-images.githubusercontent.com/47257510/52146011-dbee7880-2662-11e9-909e-635e606d001a.png)

**Desktop (please complete the following information):**
- OS: Mac OS X 10.13.6
 - Browser: Chrome 72.0.3626.81, Safari 12.0.3 (13606.4.5.3.1)
 - Oxygen: Version 2.2 Alpha 1

**Comment by Spellhammer** [comment]
This has been corrected in 2.2 Beta 1.

**Comment by WildThayne** [comment]
Im still seeing this issue in 2.2 Beta 1: https://www.screencast.com/t/yfpgH3uH5D new install, deactivated all plugins except oxygen with no change

**Comment by Spellhammer** [comment]
> Im still seeing this issue in 2.2 Beta 1: https://www.screencast.com/t/yfpgH3uH5D new install, deactivated all plugins except oxygen with no change

Can you replicate this on a Sandbox at https://oxygenbuilder.com/try ? You'll need to deactivate and remove Oxygen 2.1.2 and install Oxygen 2.2 Beta. If you're able to, please post a link to the site here and I'll take a look.
