### ISSUE TITLE
When removing a span the entire text outside of the span disappears but the text element stays

### ISSUE THREAD

**Issue by Martin-1** [soflyy/oxygen-bugs-and-features#568]
**Describe the bug**
Having a string of text with a span element in it will remove all the text when deleting the span but keeps the text element

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://graceful-rattlesnake.w5.wpsandbox.pro/sample-page/

**To Reproduce**
1. Add a section
2. Ad a textblock
3. Select part of the text and add a span to that selection
4. Delete that span

**Expected behavior**
It should only delete the span and not all of the text.

**What actually happens**
The complete text disappears but the text element stays.

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Chrome
 - Oxygen Version 3.0

**Comment by jamescrabb** [comment]
Yes very irritating

**Comment by yankiara** [comment]
Very serious bug... How comes it's been reported 3 months ago and still here?

**Comment by studiouau** [comment]
very frustrating and serious bug

**Comment by yankiara** [comment]
Any update???
Same problem inside headings.

Besides, when deleting the span, the undo popup appears quickly and disappears, so it's not even possible to cancel and you have to reload the page... provided you saved just before!

This is critical, please fix!

**Comment by jmcbade** [comment]
+1 on addressing this one

**Comment by KarzanTT** [comment]
+1

**Comment by Hud1ai2** [comment]
I don't know why the issues like this one is still there :(

**Comment by jangalomph** [comment]
Please fix! Very annoying and destructive.

**Comment by jangalomph** [comment]
Bump

**Comment by swinggraphics** [comment]
Over a year without fixing this very basic bug. This is the kind of thing that doesn't just stop me from recommending Oxygen, but makes me actively warn against using it.

**Comment by SeeJaneB** [comment]
Discovered this glitch just now. Would be great if this were fixed.

**Comment by KittenCodes** [comment]
Fixed in 3.7 Beta 1: https://oxygenbuilder.com/2021/01/22/oxygen-3-7-beta-1-now-available/.

**Comment by datascientistgonzo** [comment]
I still have the problem in 4.6.2

**Comment by bryanthatcher** [comment]
I still have a similar issue v4.6.2
Add a text block, add a span, and another and another, I have 5 spans, and only 2 show up on the front end.
