### ISSUE TITLE
Call to oxygenbuilder with HTTP - Non necessary redirection

### ISSUE THREAD

**Issue by adrien-robert** [soflyy/oxygen-bugs-and-features#713]
Hello :)

When we update extensions and we look at HTTP calls with Query Monitor plugin we can see that Oxygen use a HTTP url to call http://oxygenbuilder.com/ and then it's redirected to HTTPS, can this be fixed? So we don't get a bunch of non necessary redirections that slow the page?

![image](https://user-images.githubusercontent.com/4320990/68767001-3bc97500-0620-11ea-8160-47647640610c.png)

Thank you to consider this easy fix.

**Comment by Orelsethis** [comment]
This bug was highlighted here nearly 3 years ago, then again in issue [#2202](https://github.com/soflyy/oxygen-bugs-and-features/issues/2202) on June 2021, and it's still there in the Oxygen 4.0.3 and still slows the whole Wordpress Admin **significantly**, especially if you have both the Oxygen WooCommerce and Oxygen Gutenberg extensions added. 
On EVERY normal Wordpress Admin page, these three Oxygen plugins make the API call twice each, "EDD_SL_Plugin_Updater_Oxygen_Gutenberg->api_request()", a total of 6 redirected HTTP API calls, each of them blocks the page load for at least 1.3 seconds in my case, which adds 7.8 to 8 seconds of load time for every admin page load or action taken.
The admin plugin page is twice as bad, because it triggers the redirection 4 times for each Oxygen plugin instead of twice, so there's 12 pointless redirections, with at least 1.3 seconds blocking each, makes every action on the Wordpress admin plugin page take an additional 15+ seconds!
It's an uninformed "fix", but in the meantime, I've had to manually update the Oxygen plugin file "oxygen\component-framework\admin\updater\edd-updater.php" to force the "public $oxygen_url" to either https or even an invalid url, because although it now can't check for updates, at least then it fails the HTTP calls in less than 0.00001 seconds each, which makes my Wordpress Admin useable again.

**Comment by adrien-robert** [comment]
And I'm still here, waiting for a reply 🥲 @Spellhammer please

**Comment by Orelsethis** [comment]
After the latest set of updates, between Wordpress and Oxygen, this issue has reduced to only be on the Wordpress plugins admin page. It's stopped 6 of the unnesesary redirects that were happening on every other admin page load, so is now only doing the 6 on the plugins page itself, (used to be doubled to 12 on that page). 

That's still 6 extra seconds of blocking delay time any time that page has to reload, but it's at least useable everywhere else again. (For now at least?)

**Comment by histevenlee** [comment]
I am really enjoy oxygen's flexibility and oxygen's frontend page is pretty fast.
BUT I am so frustrated Oxygen and its eco plugins, addons slowing down my wp-admin/plugin.php page 20 seconds to 60 seconds.

Look at my plugin page.
![Plugin Page](https://user-images.githubusercontent.com/19853869/197537070-12daad1f-a35d-47f5-b4b1-0ce988740615.png)



Once I have installed Oxygen, Oxygen gutenberg, Oxygen woocommerce, these 3 plugins will generates more 8-10 http api calls, just this 3 plugins at least slowing my plugin page 5-10 seconds.

Plugin have redirection error （or **sslverify=false** SSL verification error) : oxygen, Oxygen Gutenberg, oxygen woocommerce, Hydraugen (freemius), Editor Enhancer, Spx etc.

![Oxygen 1](https://user-images.githubusercontent.com/19853869/197535585-2604afd4-86b8-47e6-8948-734897e4ba24.png)
![Oxygen 2](https://user-images.githubusercontent.com/19853869/197536183-1541ece7-9718-4ee7-aea3-b2fefd892533.png)
![Oxygen 3](https://user-images.githubusercontent.com/19853869/197536339-eb5db1c9-f5e4-48cb-aa28-13d5278a8885.png)

I always have this issue on 3-4 of my production sites, I can offer admin access if oxygen team want to check that,

**Comment by Spellhammer** [comment]
Fixed in Oxygen 4.1 beta 1.

**Comment by adrien-robert** [comment]
> Fixed in Oxygen 4.1 beta 1.

After updating an Oxygen 4.0.4 website to 4.1 beta 1, and cleared cache I still have those:
![image](https://user-images.githubusercontent.com/4320990/197787404-db0db3bb-2275-4faa-83d7-5247bca3f3f2.png)

**Comment by histevenlee** [comment]
> Fixed in Oxygen 4.1 beta 1.
Hi Elijah.
Thanks for your hard work in oxygen 4.1, I am so glad with the new 4.1 updates,  my plugins.php page are 3 seconds faster than before.

The http to https Redirection of oxygen are fixed, but the oxygen gutenberg and oxygen woocommerce still have redirections?  Will you also fix the redirection of oxygen gutenberg and oxygen woocommerce.

I also have a few ideas  or thoughts : 
I am not a developer, I am not sure if it's correct or wrong?  I found a  article explaining the HTTP API calls, https://facetwp.com/how-to-use-query-monitor-to-optimize-performance/

**Some of these API calls can happen simultaneously or take a very long time to run. Sometimes they time out if the server they are calling is temporarily busy or unavailable. If the request’s timeout setting is long (e.g. 10 seconds), the server is unresponsive and the request tries to contact the server multiple times, you’ll be waiting 20-30 seconds or even longer. All that time these requests are blocking the normal page load. This is also the reason that logging into WordPress Admin or opening the Plugins page can sometimes take a very long time.**
![image](https://user-images.githubusercontent.com/19853869/200123495-cdaf0ee6-cb7d-43cb-8a4e-548d89e5c5a3.png)


 I saw your API calls sets on 15 seconds ?  Not sure if that matters speed, but I found some API calls might have a chance takes long time if the user's network is not good (if user under proxy or VPN) 
Is it possible to tweek your plugin api call timeout from 15 seconds to a smaller number, e.g. 8 seconds or 5 seconds or other number?

When user are under proxy network or use a VPN, Oxygen or other plugins might have a SSL verify Error warning:

To fix that error warning message, below snippets works for me, put it in the functions.php or code snippets or wpcodebox / advanced scripts/Script Organizer plugin, it will eliminates the SSL verify error.

add_filter( 'https_ssl_verify', '__return_true', PHP_INT_MAX );
 
add_filter( 'http_request_args', 'http_request_force_ssl_verify', PHP_INT_MAX );
 
function http_request_force_ssl_verify( $args ) {
 
        $args[ 'sslverify' ] = true;
 
        return $args;
}

https://surniaulula.com/2018/apps/wordpress/fix-sslverifyfalse-for-plugin-theme-update-checks/


I love oxygen, I really hope oxygen success and re-earn more users.
I hope Oxygen have a big plan or maybe some future have a rewrite with advanced tech.

**Comment by Orelsethis** [comment]
Hi guys, appreciate the progress, but this is still not properly fixed and should not be marked as closed just yet.
As of Wordpress 6.1.1, Oxygen 4.1.1, Oxygen WooCommerce 2.0, Oxygen Gutenberg 1.4.3, the redirections have been removed from other WP admin pages, but are still present on the plugins/updates page for the Oxy WooComm and Oxy Gutenberg extensions, and a "sslverify=false SSL verification" error for the main Oxygen plugin. Still slowing the page loads and updates etc by 6+ seconds.
