### ISSUE TITLE
Error logs and unable to set background colors

### ISSUE THREAD

**Issue by Daniel-Richard** [soflyy/oxygen-bugs-and-features#737]
I was working on a live site and faced wasn't able to continue -- was faced with some ajax errors and saw these filling up the site's error logs.

Deprecated: Non-static method ECF_Plugin::get_font_families() should not be called statically in /.../public_html/wp-content/plugins/oxygen/component-framework/component-init.php on line 3254

(I was using ECF to add a new font for Oxygen Builder)

Notice: Undefined index: progress_bar_background_color in /.../public_html/wp-content/plugins/oxygen/component-framework/components/classes/progress-bar.class.php on line 219

Notice: Undefined index: progress_bar_bar_color in /.../public_html/wp-content/plugins/oxygen/component-framework/components/classes/progress-bar.class.php on line 235

Notice: Undefined variable: google_fonts_cache in /.../public_html/wp-content/plugins/oxygen/component-framework/includes/ajax.php on line 276

Notice: Undefined index: xlink in /.../public_html/wp-content/plugins/oxygen/component-framework/admin/cpt-templates.php on line 98

Notice: Undefined index: action in /.../public_html/wp-content/plugins/oxygen/component-framework/admin/cpt-templates.php on line 99

Notice: Undefined index: action in /.../public_html/wp-content/plugins/oxygen/component-framework/admin/cpt-templates.php on line 100

Notice: Undefined index: action in /.../public_html/wp-content/plugins/oxygen/component-framework/admin/cpt-templates.php on line 101

I hope there's a fix for these.

**Comment by KittenCodes** [comment]
@Daniel-Richard I wouldn't expect these notices to prevent you from using the builder. Are you able to replicate the issue on a Sandbox site? https://oxygenbuilder.com/try/

**Comment by KittenCodes** [comment]
Fixed in v3.6.

**Comment by wpsumo** [comment]
@KittenCodes I still get this in the builder UI:

Notice | Undefined variable: show_gradient | 1 | +wp-content/plugins/oxygen/component-framework/toolbar/views/background.view.php:167 | Plugin: oxygen
-- | -- | -- | -- | --

**Comment by KittenCodes** [comment]
> I still get this in the builder UI:
> 
> Notice	Undefined variable: show_gradient	1	+wp-content/plugins/oxygen/component-framework/toolbar/views/background.view.php:167	Plugin: oxygen

This isn't related to the original bug report. We are aware of the "Undefined variable: show_gradient" error and we have an internal bug report open to make our developers aware of it.

**Comment by wpsumo** [comment]
Ok thanks for confirming that, looking forward to the fix.

**Comment by twistedpixel** [comment]
This is NOT fixed in 3.6.1

"PHP Deprecated: Non-static method ECF_Plugin::get_font_families() should not be called statically in /var/www/vhosts/amprologix.com/stage.amprologix.com/wp-content/plugins/oxygen/component-framework/component-init.php on line 1288"

I'm getting really tired of cleaning up these problems in Oxygen's source files only to have to do it again at the next update because it's still broken. Please start testing with PHP error reporting set to E_ALL with `display_errors` turned ON and don't release updates if there are any from anything as simple as simply loading the builder. These errors prevent the builder from loading as they mess up your giant JSON configuration object and therefore it can't be parsed.

**Comment by Spellhammer** [comment]
> I'm getting really tired of cleaning up these problems in Oxygen's source files only to have to do it again at the next update because it's still broken. Please start testing with PHP error reporting set to E_ALL with display_errors turned ON and don't release updates if there are any from anything as simple as simply loading the builder. These errors prevent the builder from loading as they mess up your giant JSON configuration object and therefore it can't be parsed.

Modifying Oxygen's core files is a really bad idea. We won't support your site if we find out you've modified core files.

We do test for PHP errors and notices, but many of them don't occur in our test environment(s) because they rely on some configuration specific to your site or environment.

These non-critical errors generally only prevent you from using the builder if you have then output on the page. Try setting WP_DEBUG_DISPLAY to false.

**Comment by twistedpixel** [comment]
> Modifying Oxygen's core files is a really bad idea. We won't support your site if we find out you've modified core files.
> 
> We do test for PHP errors and notices, but many of them don't occur in our test environment(s) because they rely on some configuration specific to your site or environment.
> 
> These non-critical errors generally only prevent you from using the builder if you have then output on the page. Try setting WP_DEBUG_DISPLAY to false.

"setting WP_DEBUG_DISPLAY to false" is not a good solution. This is potentially why you miss so many of these errors/warnings/notices during your testing and why literally the same exact bug is found again in the exact same file. I like PHP errors to be displayed on development sites so I don't have to spend as much time sifting through log files. And so I don't miss things.

Also this was/is an issue with your integration with a specific plugin. A plugin that you recommend. It absolutely should be a part of your testing environment. I'm not complaining that some random plugin causes an issue with Oxygen, that would absolutely not be fair.
