### ISSUE TITLE
Pro menu mobile dropdowns don't open correctly

### ISSUE THREAD

**Issue by yankiara** [soflyy/oxygen-bugs-and-features#880]
**Describe the bug**
When clicking/touching dropdown button, menu closes, and submenu links are displayed on the page outside of the menu on mobile device.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
https://oxygen-qf4cp6nzsff8k.oxygen-demo.qsandbox.me/sample-page

**To Reproduce**
1. Edit sample page with Oxygen
2. Add a pro menu element
3. Set responsive mobile menu under 992px
4. On frontend with desktop (small screen) or mobile device, click/touch any submenu dropdown arrow.

**Expected behavior**
Dropdown should open properly on menu screen.

**What actually happens**
On mobile, menu closes and submenu links are displayed on the page.
On desktop, menu closes and nothing happens.
When reopening menu, dropdown is open.

**Screenshots**
![Screenshot_20200304_235002_com android chrome](https://user-images.githubusercontent.com/36680757/75931171-9ce9b280-5e74-11ea-8259-e7ba7651c9a3.jpg)

**Desktop (please complete the following information):**
- OS: Windows
 - Browser: Firefox and Chrome
 - Oxygen Version 3.2

**Smartphone (please complete the following information):**
- Device: Huawei P20 Pro
 - Browser: Chrome
 - Oxygen Version 3.2

**Comment by greatgraphicdesign** [comment]
I bet if you disable the animation it works, and if that's true, try disabling the animation on the media query only. Just a guess. I'm not able to test this myself at the moment.

**Comment by yankiara** [comment]
How do you deactivate dropdown animation?
I tried to delete transition time, but no change.

**Comment by greatgraphicdesign** [comment]
I finally got to my computer. Disregard my comment above. You're using the default animation, and there's no way to remove it. The only workaround I can find is to switch to off-campus mode for the mobile menu. Otherwise I see the same bug as you.

**Comment by yankiara** [comment]
Yes, too bad... This is  MAJOR MAJOR bug.

**Comment by KittenCodes** [comment]
This happens when the parent menu item has "#" as the URL. The only workaround at this time is to set an actual link for the menu item.

This issue has been replicated and reported internally.

**Comment by yankiara** [comment]
Thx so much for the tip :-)

**Comment by KittenCodes** [comment]
This has been fixed in v3.2.1 RC 1.

**Comment by createplus** [comment]
Currently running Oxygen 3.5
This is still an issue. As soon as I replaced my # links in the menu with full URLs the issue stopped.
